### ISSUE TITLE
Help with displaying inlay hints with Rust

### ISSUE THREAD

**Issue by fprasx** [AstroNvim/AstroNvim#823]
Hi, how can I configure AstroNvim so that it will display Rust inlay hints? The `rust-analyzer` docs say they are enabled by default, but the editor isn't showing them.

Out of curiosity, I looked through the logs and found this:
```
[ERROR][2022-08-02 16:37:54] .../vim/lsp/rpc.lua:420	"rpc"	"rust-analyzer"	"stderr"	'Panic context:\n> \nversion: 0.0.0 (2b472f668 2022-07-31)\nrequest: textDocument/inlayHint InlayHintParams {\n    work_done_progress_params: WorkDoneProgressParams {\n        work_done_token: None,\n    },\n    text_document: TextDocumentIdentifier {\n        uri: Url {\n            scheme: "file",\n            cannot_be_a_base: false,\n            username: "",\n            password: None,\n            host: None,\n            port: None,\n            path: "/Users/fpx/code/rust/buffer/src/main.rs",\n            query: None,\n            fragment: None,\n        },\n    },\n    range: Range {\n        start: Position {\n            line: 0,\n            character: 0,\n        },\n        end: Position {\n            line: 9,\n            character: 21,\n        },\n    },\n}\n\n'
[ERROR][2022-08-02 16:37:54] .../vim/lsp/rpc.lua:420	"rpc"	"rust-analyzer"	"stderr"	"thread 'Worker' panicked at 'Bad range: node range 0..191, range 0..199', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rowan-0.15.8/src/cursor.rs:786:13\nstack backtrace:\n"
[ERROR][2022-08-02 16:37:54] .../vim/lsp/rpc.lua:420	"rpc"	"rust-analyzer"	"stderr"	"   0: _rust_begin_unwind\n   1"
[ERROR][2022-08-02 16:37:54] .../vim/lsp/rpc.lua:420	"rpc"	"rust-analyzer"	"stderr"	": core::panicking::panic_fmt\n   2: rowan::cursor::SyntaxNode::covering_element\n   3: ide::inlay_hints::inlay_hints\n   4: std::panicking::try\n   5: ide::Analysis::inlay_hints\n   6: rust_analyzer::handlers::handle_inlay_hints\n   7: std::panicking::try\n   8: <F as threadpool::FnBox>::call_box\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"
[ERROR][2022-08-02 16:37:59] .../vim/lsp/rpc.lua:420	"rpc"	"rust-analyzer"	"stderr"	"Panic context:\n> \nversion: 0.0.0 (2b472f668 2022-07-31)\nrequest: textDocument/inlayHint InlayHintParams {\n    work_done_progress_params: WorkDoneProgressParams {\n        work_done_token: None,\n    },\n    text_document: TextDocumentIdentifier {\n        uri: Url {\n            scheme: \"file\",\n            cannot_be_a_base: false,\n            username: \"\",\n            password: None,\n            host: None,\n            port: None,\n            path: \"/Users/fpx/code/rust/buffer/src/main.rs\",\n            query: None,\n            fragment: None,\n        },\n    },\n    range: Range {\n        start: Position {\n            line: 0,\n            character: 0,\n        },\n        end: Position {\n            line: 9,\n            character: 21,\n        },\n    },\n}\n\nthread 'Worker' panicked at 'Bad range: node range 0..191, range 0..199', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rowan-0.15.8/src/cursor.rs:786:13\n"
[ERROR][2022-08-02 16:37:59] .../vim/lsp/rpc.lua:420	"rpc"	"rust-analyzer"	"stderr"	"stack backtrace:\n   0: _rust_begin_unwind\n   1: core::panicking::panic_fmt\n   2: rowan::cursor::SyntaxNode::covering_element\n   3: ide::inlay_hints::inlay_hints\n   4: std::panicking::try\n   5: ide::Analysis::inlay_hints\n   6: rust_analyzer::handlers::handle_inlay_hints\n   7: std::panicking::try\n   8: <F as threadpool::FnBox>::call_box\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"
[ERROR][2022-08-02 16:38:05] .../vim/lsp/rpc.lua:420	"rpc"	"rust-analyzer"	"stderr"	"Panic context:\n> \nversion: 0.0.0 (2b472f668 2022-07-31)\nrequest: textDocument/inlayHint InlayHintParams {\n    work_done_progress_params: WorkDoneProgressParams {\n        work_done_token: None,\n    },\n    text_document: TextDocumentIdentifier {\n        uri: Url {\n            scheme: \"file\",\n            cannot_be_a_base: false,\n            username: \"\",\n            password: None,\n            host: None,\n            port: None,\n            path: \"/Users/fpx/code/rust/buffer/src/main.rs\",\n            query: None,\n            fragment: None,\n        },\n    },\n    range: Range {\n        start: Position {\n            line: 0,\n            character: 0,\n        },\n        end: Position {\n            line: 9,\n            character: 21,\n        },\n    },\n}\n\nthread 'Worker' panicked at 'Bad range: node range 0..191, range 0..199', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rowan-0.15.8/src/cursor.rs:786:13\n"
[ERROR][2022-08-02 16:38:05] .../vim/lsp/rpc.lua:420	"rpc"	"rust-analyzer"	"stderr"	"stack backtrace:\n   0: _rust_begin_unwind\n   1: core::panicking::panic_fmt\n   2: rowan::cursor::SyntaxNode::covering_element\n   3: ide::inlay_hints::inlay_hints\n   4: std::panicking::try\n   5: ide::Analysis::inlay_hints\n   6: rust_analyzer::handlers::handle_inlay_hints\n   7: std::panicking::try\n   8: <F as threadpool::FnBox>::call_box\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"
[ERROR][2022-08-02 16:38:18] .../vim/lsp/rpc.lua:420	"rpc"	"rust-analyzer"	"stderr"	"Panic context:\n> \nversion: 0.0.0 (2b472f668 2022-07-31)\nrequest: textDocument/inlayHint InlayHintParams {\n    work_done_progress_params: WorkDoneProgressParams {\n        work_done_token: None,\n    },\n    text_document: TextDocumentIdentifier {\n        uri: Url {\n            scheme: \"file\",\n            cannot_be_a_base: false,\n            username: \"\",\n            password: None,\n            host: None,\n            port: None,\n            path: \"/Users/fpx/code/rust/buffer/src/main.rs\",\n            query: None,\n            fragment: None,\n        },\n    },\n    range: Range {\n        start: Position {\n            line: 0,\n            character: 0,\n        },\n        end: Position {\n            line: 0,\n            character: 13,\n        },\n    },\n}\n\nthread 'Worker' panicked at 'Bad range: node range 0..12, range 0..13', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rowan-0.15.8/src/cursor.rs:786:13\n"
[ERROR][2022-08-02 16:38:18] .../vim/lsp/rpc.lua:420	"rpc"	"rust-analyzer"	"stderr"	"stack backtrace:\n   0: _rust_begin_unwind\n   1: core::panicking::panic_fmt\n   2: rowan::cursor::SyntaxNode::covering_element\n   3: ide::inlay_hints::inlay_hints\n   4: std::panicking::try\n"
[ERROR][2022-08-02 16:38:18] .../vim/lsp/rpc.lua:420	"rpc"	"rust-analyzer"	"stderr"	"   5: ide::Analysis::inlay_hints\n   6: rust_analyzer::handlers::handle_inlay_hints\n   7: std::panicking::try\n   8: <F"
[ERROR][2022-08-02 16:38:18] .../vim/lsp/rpc.lua:420	"rpc"	"rust-analyzer"	"stderr"	" as threadpool::FnBox>::call_box\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"

```

This is my `rust-analyzer.lua` (edited after the above log):

```lua
return {
  settings = {
    ["rust-analyzer"] = {
      cargo = {
        loadOutDirsFromCheck = true,
      },
      checkOnSave = {
        command = "clippy",
      },
      experimental = {
        procAttrMacros = true,
      },
      -- I added this; doesn't do anything, I think I'm doing this wrong
      inlayHints = {
        typeHints = {
          enable = true
        }
      }
    },
  },
}
```

Thank you so much!

**Comment by mehalter** [comment]
Native LSP does not support inlay hints and you must use [rust-tools.nvim](https://github.com/simrat39/rust-tools.nvim) to extend the rust LSP integration to handle this. Here is an example `user/init.lua` file tat sets it up:

```lua
return {
  lsp = {
    skip_setup = { "rust_analyzer" }, -- rust-tools will handle setting up the LSP
  },
  plugins = {
    init = {
      {
        "simrat39/rust-tools.nvim",
        after = { "nvim-lspconfig", "mason-lspconfig" },
        -- Is configured via the server_registration_override installed below!
        config = function()
          require("rust-tools").setup {
            server = astronvim.lsp.server_settings "rust_analyzer", -- get the server-settings from the AstroNvim tables to allow use with lsp.server-settings and lsp.on_attach user configuration
          }
        end,
      },
    },
  },
}
```

Notice the `lsp.skip_setup` table that tells the internal LSP configuration in AstroNvim to not set up `rust_analyzer`, then when you set up `rust-tools` you want to add the `server_settings` from AstroNvim to the server settings in it's setup. This is described in the documentation in more detail here: https://astronvim.github.io/recipes/advanced_lsp#lsp-specific-plugins

**Comment by fprasx** [comment]
Thank you! I added this to my `init.lua`, but now the language server doesn't attach when I open Rust files. I tried doing `:LspStart rust_analyzer` but that just hangs (also not sure if that's even a meaningful command).

**Comment by mehalter** [comment]
Did you run a `:PackerSync` and restart to install the new `rust-tools` plugin and make sure it is running?

**Comment by fprasx** [comment]
When I do `:PackerSync` I get this error (although it says `rust-tools` is successfully installed in the packer popup).
<img width="1216" alt="Screen Shot 2022-08-04 at 11 52 22 AM" src="https://user-images.githubusercontent.com/91577249/182891299-4cb5f23f-ef34-4d82-8267-cbe73b12ea2c.png">

**Comment by mehalter** [comment]
can you please copy your user config here so I can take a look?

**Comment by fprasx** [comment]
```lua
{
  -- Configure AstroNvim updates
  updater = {
    remote = "origin", -- remote to use
    channel = "nightly", -- "stable" or "nightly"
    version = "latest", -- "latest", tag name, or regex search like "v1.*" to only do updates before v2 (STABLE ONLY)
    branch = "main", -- branch name (NIGHTLY ONLY)
    commit = nil, -- commit hash (NIGHTLY ONLY)
    pin_plugins = nil, -- nil, true, false (nil will pin plugins on stable only)
    skip_prompts = false, -- skip prompts about breaking changes
    show_changelog = true, -- show the changelog after performing an update
    -- remotes = { -- easily add new remotes to track
    --   ["remote_name"] = "https://remote_url.come/repo.git", -- full remote url
    --   ["remote2"] = "github_user/repo", -- GitHub user/repo shortcut,
    --   ["remote3"] = "github_user", -- GitHub user assume AstroNvim fork
    -- },
  },

  -- Set colorscheme
  colorscheme = "nord",

  -- Override highlight groups in any theme
  highlights = {
    -- duskfox = { -- a table of overrides
    --   Normal = { bg = "#000000" },
    -- },
    default_theme = function(highlights) -- or a function that returns one
      local C = require "default_theme.colors"

      highlights.Normal = { fg = C.fg, bg = C.bg }
      return highlights
    end,
  },

  -- set vim options here (vim.<first_key>.<second_key> =  value)
  options = {
    opt = {
      relativenumber = true, -- sets vim.opt.relativenumber
      termguicolors = true,
    },
    g = {
      mapleader = " ", -- sets vim.g.mapleader
    },
  },

  -- Default theme configuration
  default_theme = {
    diagnostics_style = { italic = true },
    -- Modify the color table
    colors = {
      fg = "#abb2bf",
    },
    plugins = { -- enable or disable extra plugin highlighting
      aerial = true,
      beacon = false,
      bufferline = true,
      dashboard = true,
      highlighturl = true,
      hop = false,
      indent_blankline = true,
      lightspeed = false,
      ["neo-tree"] = true,
      notify = true,
      ["nvim-tree"] = false,
      ["nvim-web-devicons"] = true,
      rainbow = true,
      symbols_outline = false,
      telescope = true,
      vimwiki = false,
      ["which-key"] = true,
    },
  },

  -- Disable AstroNvim ui features
  ui = {
    nui_input = true,
    telescope_select = true,
  },

  -- Configure plugins
  plugins = {
    -- Add plugins, the packer syntax without the "use"
    init = {
      -- You can disable default plugins as follows:
      -- ["goolord/alpha-nvim"] = { disable = true },

      -- You can also add new plugins here as well:
      -- { "andweeb/presence.nvim" },
      -- {
      --   "ray-x/lsp_signature.nvim",
      --   event = "BufRead",
      --   config = function()
      --     require("lsp_signature").setup()
      --   end,
      -- },
      {
        "arcticicestudio/nord-vim",
        as = "nord",
      },
    },
    -- All other entries override the setup() call for default plugins
    ["null-ls"] = function(config)
      local null_ls = require "null-ls"
      -- Check supported formatters and linters
      -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/formatting
      -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/diagnostics
      config.sources = {
        -- Set a formatter
        null_ls.builtins.formatting.stylua,
        null_ls.builtins.formatting.prettier,
      }
      -- set up null-ls's on_attach function
      config.on_attach = function(client)
        -- NOTE: You can remove this on attach function to disable format on save
        if client.resolved_capabilities.document_formatting then
          vim.api.nvim_create_autocmd("BufWritePre", {
            desc = "Auto format before save",
            pattern = "<buffer>",
            callback = vim.lsp.buf.formatting_sync,
          })
        end
      end
      return config -- return final config table
    end,
    treesitter = {
      ensure_installed = { "lua" },
    },
    -- use mason-lspconfig to configure LSP installations
    ["mason-lspconfig"] = {
      ensure_installed = { "sumneko_lua" },
    },
    -- use mason-tool-installer to configure DAP/Formatters/Linter installation
    ["mason-tool-installer"] = {
      ensure_installed = { "prettier", "stylua" },
    },
    packer = {
      compile_path = vim.fn.stdpath "data" .. "/packer_compiled.lua",
    },
  },

  -- LuaSnip Options
  luasnip = {
    -- Add paths for including more VS Code style snippets in luasnip
    vscode_snippet_paths = {},
    -- Extend filetypes
    filetype_extend = {
      javascript = { "javascriptreact" },
    },
  },

  -- CMP Source Priorities
  -- modify here the priorities of default cmp sources
  -- higher value == higher priority
  -- The value can also be set to a boolean for disabling default sources:
  -- false == disabled
  -- true == 1000
  cmp = {
    source_priority = {
      nvim_lsp = 1000,
      luasnip = 750,
      buffer = 500,
      path = 250,
    },
  },

  -- Extend LSP configuration
  lsp = {
    -- enable servers that you already have installed without mason
    skip_setup = {
      "rust_analyzer",
    },
    plugins = {
      init = {
        {
          "simrat39/rust-tools.nvim",
          after = { "nvim-lspconfig", "mason-lspconfig" },
          -- Is configured via the server_registration_override installed below!
          config = function()
            require("rust-tools").setup {
              -- get the server-settings from the AstroNvim tables to allow use with lsp.server-settings and lsp.on_attach user configuration
              server = astronvim.lsp.server_settings "rust_analyzer",
            }
          end,
        },
      },
    },
    -- easily add or disable built in mappings added during LSP attaching
    mappings = {
      n = {
        -- ["<leader>lf"] = false -- disable formatting keymap
      },
    },
    -- add to the server on_attach function
    -- on_attach = function(client, bufnr)
    -- end,

    -- override the lsp installer server-registration function
    -- server_registration = function(server, opts)
    --   require("lspconfig")[server].setup(opts)
    -- end,

    -- Add overrides for LSP server settings, the keys are the name of the server
    ["server-settings"] = {
      -- example for addings schemas to yamlls
      -- yamlls = {
      --   settings = {
      --     yaml = {
      --       schemas = {
      --         ["http://json.schemastore.org/github-workflow"] = ".github/workflows/*.{yml,yaml}",
      --         ["http://json.schemastore.org/github-action"] = ".github/action.{yml,yaml}",
      --         ["http://json.schemastore.org/ansible-stable-2.9"] = "roles/tasks/*.{yml,yaml}",
      --       },
      --     },
      --   },
      -- },
    },
  },

  -- Diagnostics configuration (for vim.diagnostics.config({}))
  diagnostics = {
    virtual_text = true,
    underline = true,
  },

  -- Mapping data with "desc" stored directly by vim.keymap.set().
  --
  -- Please use this mappings table to set keyboard mapping since this is the
  -- lower level configuration and more robust one. (which-key will
  -- automatically pick-up stored data by this setting.)
  mappings = {
    -- first key is the mode
    n = {
      -- second key is the lefthand side of the map
      -- mappings seen under group name "Buffer"
      ["<leader>bb"] = { "<cmd>tabnew<cr>", desc = "New tab" },
      ["<leader>bc"] = { "<cmd>BufferLinePickClose<cr>", desc = "Pick to close" },
      ["<leader>bj"] = { "<cmd>BufferLinePick<cr>", desc = "Pick to jump" },
      ["<leader>bt"] = { "<cmd>BufferLineSortByTabs<cr>", desc = "Sort by tabs" },
      -- quick save
      -- ["<C-s>"] = { ":w!<cr>", desc = "Save File" },  -- change description but the same command
    },
    t = {
      -- setting a mapping to false will disable it
      -- ["<esc>"] = false,
    },
  },

  -- Modify which-key registration (Use this with mappings table in the above.)
  ["which-key"] = {
    -- Add bindings which show up as group name
    register_mappings = {
      -- first key is the mode, n == normal mode
      n = {
        -- second key is the prefix, <leader> prefixes
        ["<leader>"] = {
          -- third key is the key to bring up next level and its displayed
          -- group name in which-key top level menu
          ["b"] = { name = "Buffer" },
        },
      },
    },
  },

  -- This function is run last
  -- good place to configuring augroups/autocommands and custom filetypes
  polish = function()
    -- Set key binding
    -- Set autocommands
    vim.api.nvim_create_augroup("packer_conf", { clear = true })
    vim.api.nvim_create_autocmd("BufWritePost", {
      desc = "Sync packer after modifying plugins.lua",
      group = "packer_conf",
      pattern = "plugins.lua",
      command = "source <afile> | PackerSync",
    })

    -- Set up custom filetypes
    -- vim.filetype.add {
    --   extension = {
    --     foo = "fooscript",
    --   },
    --   filename = {
    --     ["Foofile"] = "fooscript",
    --   },
    --   pattern = {
    --     ["~/%.config/foo/.*"] = "fooscript",
    --   },
    -- }
  end,
}

return config
```

Thank you so much for the help!

**Comment by mehalter** [comment]
```lua
after = { "nvim-lspconfig", "mason-lspconfig" },
```

This should be `mason-lspconfig.nvim` as I had in the code block that I sent you :)

**Comment by mehalter** [comment]
also wait, it also appears that you put the `plugins` table into the wrong location. One second and I will fix it and send you a new version

**Comment by fprasx** [comment]
It's still giving that error :(

**Comment by mehalter** [comment]
```lua
local config = {
  -- Configure AstroNvim updates
  updater = {
    remote = "origin", -- remote to use
    channel = "nightly", -- "stable" or "nightly"
    version = "latest", -- "latest", tag name, or regex search like "v1.*" to only do updates before v2 (STABLE ONLY)
    branch = "main", -- branch name (NIGHTLY ONLY)
    commit = nil, -- commit hash (NIGHTLY ONLY)
    pin_plugins = nil, -- nil, true, false (nil will pin plugins on stable only)
    skip_prompts = false, -- skip prompts about breaking changes
    show_changelog = true, -- show the changelog after performing an update
    -- remotes = { -- easily add new remotes to track
    --   ["remote_name"] = "https://remote_url.come/repo.git", -- full remote url
    --   ["remote2"] = "github_user/repo", -- GitHub user/repo shortcut,
    --   ["remote3"] = "github_user", -- GitHub user assume AstroNvim fork
    -- },
  },

  -- Set colorscheme
  colorscheme = "nord",

  -- Override highlight groups in any theme
  highlights = {
    -- duskfox = { -- a table of overrides
    --   Normal = { bg = "#000000" },
    -- },
    default_theme = function(highlights) -- or a function that returns one
      local C = require "default_theme.colors"

      highlights.Normal = { fg = C.fg, bg = C.bg }
      return highlights
    end,
  },

  -- set vim options here (vim.<first_key>.<second_key> =  value)
  options = {
    opt = {
      relativenumber = true, -- sets vim.opt.relativenumber
      termguicolors = true,
    },
    g = {
      mapleader = " ", -- sets vim.g.mapleader
    },
  },

  -- Default theme configuration
  default_theme = {
    diagnostics_style = { italic = true },
    -- Modify the color table
    colors = {
      fg = "#abb2bf",
    },
    plugins = { -- enable or disable extra plugin highlighting
      aerial = true,
      beacon = false,
      bufferline = true,
      dashboard = true,
      highlighturl = true,
      hop = false,
      indent_blankline = true,
      lightspeed = false,
      ["neo-tree"] = true,
      notify = true,
      ["nvim-tree"] = false,
      ["nvim-web-devicons"] = true,
      rainbow = true,
      symbols_outline = false,
      telescope = true,
      vimwiki = false,
      ["which-key"] = true,
    },
  },

  -- Disable AstroNvim ui features
  ui = {
    nui_input = true,
    telescope_select = true,
  },

  -- Configure plugins
  plugins = {
    -- Add plugins, the packer syntax without the "use"
    init = {
      -- You can disable default plugins as follows:
      -- ["goolord/alpha-nvim"] = { disable = true },

      -- You can also add new plugins here as well:
      -- { "andweeb/presence.nvim" },
      -- {
      --   "ray-x/lsp_signature.nvim",
      --   event = "BufRead",
      --   config = function()
      --     require("lsp_signature").setup()
      --   end,
      -- },
      {
        "arcticicestudio/nord-vim",
        as = "nord",
      },
      {
        "simrat39/rust-tools.nvim",
        after = { "nvim-lspconfig", "mason-lspconfig.nvim" },
        -- Is configured via the server_registration_override installed below!
        config = function()
          require("rust-tools").setup {
            -- get the server-settings from the AstroNvim tables to allow use with lsp.server-settings and lsp.on_attach user configuration
            server = astronvim.lsp.server_settings "rust_analyzer",
          }
        end,
      },
    },
    -- All other entries override the setup() call for default plugins
    ["null-ls"] = function(config)
      local null_ls = require "null-ls"
      -- Check supported formatters and linters
      -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/formatting
      -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/diagnostics
      config.sources = {
        -- Set a formatter
        null_ls.builtins.formatting.stylua,
        null_ls.builtins.formatting.prettier,
      }
      -- set up null-ls's on_attach function
      config.on_attach = function(client)
        -- NOTE: You can remove this on attach function to disable format on save
        if client.resolved_capabilities.document_formatting then
          vim.api.nvim_create_autocmd("BufWritePre", {
            desc = "Auto format before save",
            pattern = "<buffer>",
            callback = vim.lsp.buf.formatting_sync,
          })
        end
      end
      return config -- return final config table
    end,
    treesitter = {
      ensure_installed = { "lua" },
    },
    -- use mason-lspconfig to configure LSP installations
    ["mason-lspconfig"] = {
      ensure_installed = { "sumneko_lua" },
    },
    -- use mason-tool-installer to configure DAP/Formatters/Linter installation
    ["mason-tool-installer"] = {
      ensure_installed = { "prettier", "stylua" },
    },
    packer = {
      compile_path = vim.fn.stdpath "data" .. "/packer_compiled.lua",
    },
  },

  -- LuaSnip Options
  luasnip = {
    -- Add paths for including more VS Code style snippets in luasnip
    vscode_snippet_paths = {},
    -- Extend filetypes
    filetype_extend = {
      javascript = { "javascriptreact" },
    },
  },

  -- CMP Source Priorities
  -- modify here the priorities of default cmp sources
  -- higher value == higher priority
  -- The value can also be set to a boolean for disabling default sources:
  -- false == disabled
  -- true == 1000
  cmp = {
    source_priority = {
      nvim_lsp = 1000,
      luasnip = 750,
      buffer = 500,
      path = 250,
    },
  },

  -- Extend LSP configuration
  lsp = {
    -- enable servers that you already have installed without mason
    skip_setup = {
      "rust_analyzer",
    },
    -- easily add or disable built in mappings added during LSP attaching
    mappings = {
      n = {
        -- ["<leader>lf"] = false -- disable formatting keymap
      },
    },
    -- add to the server on_attach function
    -- on_attach = function(client, bufnr)
    -- end,

    -- override the lsp installer server-registration function
    -- server_registration = function(server, opts)
    --   require("lspconfig")[server].setup(opts)
    -- end,

    -- Add overrides for LSP server settings, the keys are the name of the server
    ["server-settings"] = {
      -- example for addings schemas to yamlls
      -- yamlls = {
      --   settings = {
      --     yaml = {
      --       schemas = {
      --         ["http://json.schemastore.org/github-workflow"] = ".github/workflows/*.{yml,yaml}",
      --         ["http://json.schemastore.org/github-action"] = ".github/action.{yml,yaml}",
      --         ["http://json.schemastore.org/ansible-stable-2.9"] = "roles/tasks/*.{yml,yaml}",
      --       },
      --     },
      --   },
      -- },
    },
  },

  -- Diagnostics configuration (for vim.diagnostics.config({}))
  diagnostics = {
    virtual_text = true,
    underline = true,
  },

  -- Mapping data with "desc" stored directly by vim.keymap.set().
  --
  -- Please use this mappings table to set keyboard mapping since this is the
  -- lower level configuration and more robust one. (which-key will
  -- automatically pick-up stored data by this setting.)
  mappings = {
    -- first key is the mode
    n = {
      -- second key is the lefthand side of the map
      -- mappings seen under group name "Buffer"
      ["<leader>bb"] = { "<cmd>tabnew<cr>", desc = "New tab" },
      ["<leader>bc"] = { "<cmd>BufferLinePickClose<cr>", desc = "Pick to close" },
      ["<leader>bj"] = { "<cmd>BufferLinePick<cr>", desc = "Pick to jump" },
      ["<leader>bt"] = { "<cmd>BufferLineSortByTabs<cr>", desc = "Sort by tabs" },
      -- quick save
      -- ["<C-s>"] = { ":w!<cr>", desc = "Save File" },  -- change description but the same command
    },
    t = {
      -- setting a mapping to false will disable it
      -- ["<esc>"] = false,
    },
  },

  -- Modify which-key registration (Use this with mappings table in the above.)
  ["which-key"] = {
    -- Add bindings which show up as group name
    register_mappings = {
      -- first key is the mode, n == normal mode
      n = {
        -- second key is the prefix, <leader> prefixes
        ["<leader>"] = {
          -- third key is the key to bring up next level and its displayed
          -- group name in which-key top level menu
          ["b"] = { name = "Buffer" },
        },
      },
    },
  },

  -- This function is run last
  -- good place to configuring augroups/autocommands and custom filetypes
  polish = function()
    -- Set key binding
    -- Set autocommands
    vim.api.nvim_create_augroup("packer_conf", { clear = true })
    vim.api.nvim_create_autocmd("BufWritePost", {
      desc = "Sync packer after modifying plugins.lua",
      group = "packer_conf",
      pattern = "plugins.lua",
      command = "source <afile> | PackerSync",
    })

    -- Set up custom filetypes
    -- vim.filetype.add {
    --   extension = {
    --     foo = "fooscript",
    --   },
    --   filename = {
    --     ["Foofile"] = "fooscript",
    --   },
    --   pattern = {
    --     ["~/%.config/foo/.*"] = "fooscript",
    --   },
    -- }
  end,
}

return config
```

**Comment by fprasx** [comment]
Ok I see. It's still giving the error! I'm going to `:PackerClean`, restart my computer, and see what happens. 

I really appreciate the help! I'm pretty new to lua and neovim.

**Comment by Bash-09** [comment]
I've tried to recreate the steps in this issue, however I am getting the error `packer.nvim: Error running config for rust-tools.nvim: [string "..."]:0: attempt to index field 'lsp' (a nil value)`

Attached is my `init.lua` if that is useful.
[init.lua.txt](https://github.com/AstroNvim/AstroNvim/files/9268685/init.lua.txt)

**Comment by mehalter** [comment]
@Bash-09 what version of AstroNvim are you using? `:AstroVersion`

**Comment by Bash-09** [comment]
> @Bash-09 what version of AstroNvim are you using? `:AstroVersion`

`Version: v1.7.0-6-g5dfeb77`

**Comment by Bash-09** [comment]
@mehalter Ah yeah I probably should have tried that, it seems to have worked. Thanks so much for lending me your time to help!

**Comment by odecay** [comment]
Any pointers for enabling rust-tools and format on write with rust-analyzer?

**Comment by mehalter** [comment]
@odecay you can do something like this as your `user/init.lua`:

```lua
return {
  lsp = {
    skip_setup = { "rust_analyzer" }, -- skip lsp setup because rust-tools will do it itself
    on_attach = function(client)
      -- enable formatting on save if client supports it
      if client.resolved_capabilities.document_formatting then
        vim.api.nvim_create_autocmd("BufWritePre", {
          desc = "Auto format before save",
          pattern = "<buffer>",
          callback = function() vim.lsp.buf.formatting_sync() end,
        })
      end
    end
  },
  plugins = {
    init = {
      {
        "simrat39/rust-tools.nvim",
        after = "mason-lspconfig.nvim", -- make sure to load after mason-lspconfig
        config = function()
          require("rust-tools").setup {
            server = astronvim.lsp.server_settings "rust_analyzer", -- get the server settings and built in capabilities/on_attach
          }
        end,
      },
    },
    ["mason-lspconfig"] = {
      ensure_installed = { "rust_analyzer" }, -- install rust_analyzer
    },
  },
}
```

**Comment by odecay** [comment]
Awesome, this snippet was what I wanted, I had put an autocommand in the polish section that was similar but on `*.rs` pattern, but this seems a lot cleaner.

Thank you :+1:

**Comment by mehalter** [comment]
No problem! When AstroNvim v2.0 is released in the coming months formatting on save will be a default option which will save a decent amount of this code. Sorry for any confusion or extra leg work needed to get this up and running!

**Comment by blastrock** [comment]
Does someone have a config for the latest astronvim? It looks like rust-tools is depracated, and it has been [replaced by ferris](https://github.com/AstroNvim/astrocommunity/issues/706), even if rust-tools recommended rustaceanvim. A lot of config snippets are for older versions of astrolsp, and I can't figure out how to get the inlay hints for my variable declarations. I'd appreciate some help.

**Comment by mehalter** [comment]
@blastrock the rust pack in AstroCommunity sets up inlay hunts by default. You can either enable it by default in your AstroLSP configuration or toggle them on with `<Leader>uh`

**Comment by blastrock** [comment]
Thank you, got them to work!

I'll add this for the next reader: inlay hints with rustaceanvim do not work with nvim 0.9, you need 0.10.
